//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entity.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtTasMarking
    {
        public System.Guid ID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> MarkingTime { get; set; }
        public Nullable<System.DateTime> ForDate { get; set; }
        public Nullable<System.DateTime> CheckingTime { get; set; }
        public Nullable<int> CheckBy { get; set; }
        public string MarkingComment { get; set; }
        public string CheckingComment { get; set; }
    }
}
