//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entity.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtTask
    {
        public string GroupName { get; set; }
        public string TaskName { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<System.DateTime> ScheduledTime { get; set; }
        public int ID { get; set; }
    }
}
