//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entity.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtUser
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ResetKey { get; set; }
        public Nullable<System.DateTime> ResetKeyExpiry { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    }
}
